sudo: false  # Use container-based infrastructure
language: python
python:
  - "3.6"
  - "3.7"
git:
  # don't need the default depth of 50
  # but don't want to use a depth of 1 since that affects
  # whether jobs run when you have multiple commits queued
  # https://github.com/travis-ci/travis-ci/issues/4575
  depth: 10
addons:
  apt:
    packages:
      # Needed for NetMHC
      - tcsh
cache:
  # cache pip files, also directory used for Ensembl downloads of GTF and FASTA files
  # along with the indexed db of intervals and ID mappings and pickles
  # of sequence dictionaries
  pip: true
  directories:
    - $HOME/.cache/pyensembl/
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - python --version
  # install netmhcbundle: needed for mhctools tests
  - git clone https://mhcbundle:$MHC_BUNDLE_PASS@github.com/openvax/netmhc-bundle.git
  - export NETMHC_BUNDLE_HOME=$PWD/netmhc-bundle
  - mkdir tmp
  - export NETMHC_BUNDLE_TMPDIR=$PWD/tmp
  - export PATH=$PATH:$NETMHC_BUNDLE_HOME/bin
  # we want to include mhctools and vaxrank unit tests as a general integration test to make sure
  # the stack isn't broken in an obvious way
  - git clone https://github.com/openvax/mhctools.git
env:
  global:
    # MHC_BUNDLE_PASS
    - secure: "WbchjXY8MhdOb/eoHb75Sx80ucT70bNsvWtFTszXqXOkEsvA4EB4QkgdCRUvK1p6pOAnNYjFwctacJv76PlHJUnaZUv3KYCIGHQaJI6r82/u7BzALKl4DAP2gUhxVjmnHd/CaK6USiDemdROw6x5RToN9q/0wD6CLMYFatcjSgeLJ6J1fCIDA9frQWy7U04khIA5rNrIVBSpChifLBxnHm0oTXA0vExb5iNjMFLtkTIVOx6PQCeBv3XQdvzBTmdhA16zWPFwQq2lBJ+dFIsC4PprO+gPzL3afS/Mmk88pArAVv0/RZeAGOtvJKVdAs+h66ioVq0r6/3klkiNwNTC8f4c8UfVaQSuAIJ5/Kj+5XmNxQAje5ZQ8U+YDmm3FXRx6vaV83134LOHWVX1rK9lspqGfrkoidYQq6ENfnlN5G1G/TZiE2aX72eU65f+vUbgNWRSAnemd2Sa0s9P92XzKqwvd9QLSMNvDAnbvW2n8Pl48hIj9zbAemI1V52Ro6yuWPiNkfpbfhQ9QYd6Okwyz7A2aHh99ulc+RxLZgDpJP/KNNzywQvWyJtGigI+6/PAW0rJ8E3Z2lDL3ZAcRtc0Hom/gR3lAhJBmhbIWfSer4INTJ0JG4spOS/KBJvh42Aon1W73fwf8Nao9AXWDACNg5HOFoE6yk6ICsVBgcC2tDI="
    - KERAS_BACKEND=tensorflow
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      nose pylint pandoc keras tensorflow
  - source activate test-environment
  - python --version #  make sure we're running the Python version we expect
  - pip install pypandoc
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
  # install mhctools, vaxrank and its dependent data
  - pip install --upgrade -r $PWD/mhctools/requirements.txt
before_script:
  # needed for MHCflurry predictor test
  - mhcflurry-downloads fetch
script:
  - ./lint.sh
  # this command runs both mhctools and vaxrank tests. Sometimes they don't print output for a long
  # time; travis_wait extends the time allowed with no output.
  - >
    nosetests -sv test --with-coverage --cover-package=mhcnames -a '!skip' &&
    nosetests -sv -a "!skip" $PWD/mhctools/test
after_success:
  coveralls
deploy:
  provider: pypi
  distributions: sdist
  user: openvax
  password: # See http://docs.travis-ci.com/user/encryption-keys/
      secure: "ZzskPyarYLTHTxxTAvD4IVmA7m/YsLlo4ARdXaSGPoIvsMRcv44PxodU+tSBSHW1GdiYzeZvpOa5dVBYr/SrnDVeGUhf6TEzw/oUuTgE22cXpBLPpXO2XOFW0Qy8HNaNJJyyZ2BX9hxhBhTRV2llDbaB02tfPjG/7ApUZT9oJzm6rAW+Ukzjw5tWbpP2cDJc3MhcPwtMGpXILcwA0OTxX61WketGe++Drefwy0jtsrzNEQyezXUY1n12AIgVh8xNbqWGKo0jf9PtddFUO4t6r+X+ITNtZKspsE9RQwqVZLdoKmWG2PSX2dcGRKAXSXrflfvmx7VhSJcsHSKZGbY70QoUTz2hjNgT6nCRq2EMen5RSZUOPFJVla4TSXNj5CUigtEDweqk+jZxi8CqrNrsAKVhudT8kyHrEmtFCsx5DGKZ3gN2CzQbkXKU4VMG/6endBeGZoMNLqPBzCQP9bbAzCsMu8bYFCGByFTpB5KeiPosLftaTaYd7URnwZvZJmXUVJ1MYs+T/bTY74O7Enix2rKa9V7Cw1y2V6/tVzyTzTAW3eX9yokOePZoMutHKvdEh5AWdsa1KZTmRHJeUeA+aY5owXEiu7I4ElsdsRiYC/2vlvlVrbw02vR5GSXZH89xOOXNFKQEnrGagYmglw4Ao625N5Clh4RUAeQ38jViS6Q="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
